<?php

namespace VdPoel\Concur\Test\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Contracts\Auth\Authenticatable;
use VdPoel\Concur\Events\TravelProfile\LookupTravelProfile;

class Account extends Model implements Authenticatable
{
    protected $fillable = [
        'first_name',
        'last_name',
        'email'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function (Account $account) {
            event(LookupTravelProfile::class, [$account]);
        });
    }

    public function getAuthIdentifierName()
    {
        return 'id';
    }

    public function getAuthIdentifier()
    {
        return $this->getKey();
    }

    public function getAuthPassword()
    {
        return 'secret';
    }

    public function getRememberToken()
    {
        return 'token';
    }

    public function setRememberToken($value)
    {
        $this->setAttribute('remember_token', $value);
    }

    public function getRememberTokenName()
    {
        return 'remember_token';
    }
}
